apiVersion: apps/v1
kind: Deployment
metadata:
  name: karaoke-frontend
  labels:
    app: karaoke-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karaoke-frontend
  template:
    metadata:
      labels:
        app: karaoke-frontend
    spec:
      containers:
      - name: karaoke-frontend
        image: esubalewdavid/karaoke-frontend
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"