apiVersion: apps/v1
kind: Deployment
metadata:
  name: karaoke-frontend-gke
  labels:
    app: karaoke-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karaoke-frontend
  template:
    metadata:
      labels:
        app: karaoke-frontend
    spec:
      containers:
      - name: karaoke-frontend-gke
        image: esubalewdavid/karaoke-frontend
        ports:
        - containerPort: 80
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"