apiVersion: v1
kind: Service
metadata:
  name: karaoke-frontend-service
  labels:
    app: karaoke-frontend
spec:
  selector:
    app: karaoke-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer